openapi: 3.0.0

info:
  title: Todo List Backend API
  description: This is the backend api for my first todo list project including frontend.
  version: 1.0.0
  contact:
    name: Piyush Jiwane
    email: jiwane@gmail.com

servers:
  - url: http://localhost:5000
    description: This is the local server

paths:
  /todo/api/v1/refreshToken:
    $ref: 'jwtToken.yml#/paths/~1todo~1api~1v1~1refreshToken'
  /todo/api/v1/login:
    $ref: './login.yml#/paths/~1todo~1api~1v1~1login'
  /todo/api/v1/forgetPassword:
    $ref: './login.yml#/paths/~1todo~1api~1v1~1forgetPassword'
  /todo/api/v1/updateUser/{userId}:
    $ref: './login.yml#/paths/~1todo~1api~1v1~1updateUser~1{userId}'
  /todo/api/v1/deleteUser/{userId}:
    $ref: './login.yml#/paths/~1todo~1api~1v1~1deleteUser~1{userId}'
  /todo/api/v1/checkUser:
    $ref: './signup.yml#/paths/~1todo~1api~1v1~1checkUser'
  /todo/api/v1/otpValidation:
    $ref: './signup.yml#/paths/~1todo~1api~1v1~1otpValidation'
  /todo/api/v1/signup:
    $ref: './signup.yml#/paths/~1todo~1api~1v1~1signup'
  /todo/api/v1/todo/{userId}:
    $ref: './todo.yml#/paths/~1todo~1api~1v1~1todo~1{userId}'
  /todo/api/v1/inActive/todo/{userId}:
    $ref: 'todo.yml#/paths/~1todo~1api~1v1~1inActive~1todo~1{userId}'
  /todo/api/v1/update/todo/{userId}:
    $ref: 'todo.yml#/paths/~1todo~1api~1v1~1update~1todo~1{userId}'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT